#! /bin/bash

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent`
fi

if [[ -z $1 ]]; then
    echo -e "You must pass in a commit message"
    exit
fi

NOW=$(date +"%m-%d-%Y")

sshadd
git status
git add .
git status
git commit -m "$1: $NOW"
git push

