#! /bin/bash
DESTDIR="$HOME/Git/charliecalvert.github.io/books/CloudNotes/Prog109"
SRCDIR="$HOME/Git/prog109-notes/"

# cp -vr *.html $DESTDIR/.

function git-commit() {
	cd $DESTDIR
	git add .
	git commit -m "send $NOW"
	git push
}

rsync -avu --delete --exclude=.git --exclude=.idea --exclude=old "$SRCDIR" "$DESTDIR"
git-commit
