<ol>
	<li><a href="/charlie/development/database/NoSql/CouchDb.html">CouchDb</a></li>
	<li><a href="/charlie/development/database/NoSql/MongoDb.html">MongoDb</a></li>
	<li><a href="/charlie/development/database/mssql/sql-commands.html">SQL-Commands</a></li>
	<li><a href="/charlie/development/database/able-baker.html">AbleBaker</a></li>
	<li><a href="/charlie/development/database/mysql/index.html">MySQL</a></li>
	<li><a href="/charlie/development/database/mssql/datasets-commits.html">DataSet Commit</a></li>
	<li><a href="/charlie/development/database/mssql/dataset-master-detail.html">DataSet Master Detail</a></li>
	<li><a href="/charlie/development/database/data/facts/index.html">Facts</a></li>
	<li><a href="/charlie/development/database/data/LinqIntroWeb/LinqIntroWeb.html">LINQ Intro Video</a></li>
</ol>
